- id: check-untitled
  name: check-untitled
  description: check if i am committing an empty markdown file
  entry: check-untitled
  language: system
  pass_filenames: false
  files: ^(.*/)?Untitled\.md$
